### ISSUE TITLE
How to know when subjects are fully processed?

### ISSUE THREAD

**Issue by vnbcs** [khanlab/hippunfold#273]
Is there a way to quickly check if a subject is fully processed? Currently I'm checking for the presence of the `qc` folder in the output, but I'm worried that the subjects with a `qc` folder might not actually be done. I'm guessing there's a way to find this information in the logs, but I'm not sure what to look for. In addition to the logs saved in `hippunfold/logs`, I also save all the command line output to a separate log file. 

Context: I'm running hippunfold using slurm (job scheduler), and I keep underestimating the amount of time needed to run the whole program, so not all the subjects finish by the time the jobs terminate. I'm not capable of actually looking at the imaging results - I'm running way too many subjects to manually check the contents of each folder. 

Thanks!

**Comment by jordandekraker** [comment]
The easiest way to check is to see whether `hippunfold/work/<YOUR_SUBJECT>_work.tar.gz` exists, since this is the final step of the HippUnfold pipeline.

A few other tips:
- Subjects that have already been completed will not be rerun unless you specify. Hippunfold will also pick up processing where it was left off if a job was killed (as long as the output directory remains accessible)
- Snakemake can submit its own jobs via slurm, and therefore hippunfold will accept these same arguments. Check it out [here](https://snakemake.readthedocs.io/en/v7.19.1/executing/cluster.html). Note that the required files will need to be in network-accessible directories!

I hope that helps!
