### ISSUE TITLE
Laplace gradient not same domain as grey matter labels

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#40]
@Bradley-Karat and I noticed this as Brad was trying to look at gradients of the Laplace fields in space-cropT1w. 

I think the problem is resampling from space-corobl to space-cropT1w. This is performed using `--interpolation MultiLabel` for labelmaps, but `--interpolation NearestNeighbor` for Laplace coords, which could lead to non-overlapping domains, as shown below.
Laplace field (AP):
<img width="470" alt="Screen Shot 2021-03-19 at 10 34 53 AM" src="https://user-images.githubusercontent.com/25106300/111802633-9920a680-88a4-11eb-8fd8-20d9cd3277de.png">
Subfield labelmap overlaid on Laplace field (AP):
<img width="470" alt="Screen Shot 2021-03-19 at 10 34 53 AM" src="https://user-images.githubusercontent.com/25106300/111802634-9920a680-88a4-11eb-90c6-17277a59006e.png">

This resampling also seems to create distortions in the Laplace field, which is shown here when you take their gradients:
Gradient of Laplace field (AP) (different slice from above):
![Screenshot from 2021-03-19 11-12-55](https://user-images.githubusercontent.com/25106300/111802613-92922f00-88a4-11eb-86f7-a4466c63eee2.png)

Some solutions I can think of:
1) perform analyses like this examination of Laplace gradients in space-corobl. 
2) post-process the Laplace coords in space-cropT1w (ie. by interpolating any missing voxels and then perhaps also applying smoothing or `laplace_iters.m` to make the gradients smooth).
3) create some custom code for resampling Laplace coords. This could be done by extrapolating the coords in space-corobl around the hippocampus and then `--interpolation Linear` while resampling to space-cropT1w, and then masking out non GM points. I think (but am not certain) that this would lead to smooth gradients of the resampled Laplace coords. 

\1) is simpler but less friendly for future users. 2) and 3) are a bit post-hoc, but would mean people can more easily play around with the gradients in space-cropT1w in the future. Let me know what you guys think is best!

**Comment by akhanf** [comment]
Sorry didn't see this till Brad brought it up today, I think my email notifications have been going to spam!

Yes these differences are due to the nearest neighbour vs multi-label interpolation. 

Something like Option 3 would be the way to go, to at least make sure the outer boundary is defined by the same multi-label interpolated mask -- but ensuring the coords are smoothly interpolated would have to be a bit hacky -- e.g. extrapolating somewhat before transforming with linear interpolation. Whatever we end up doing we should make sure we are not accidentally corrupting things though.. 

If one of you wants to create a PR to start this that would be great, otherwise I can try to look at it some time in the next week or two..
