### ISSUE TITLE
which T2w image(s) to pull

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#48]
Ali noted that when using the `--skip_preproc` flag, only the first T2w image in a directory is used (instead of the usual behaviour of averaging multiple scans). We should have a systematic way to determining which scan gets pulled. Perhaps a sorting key.

I think priority should be given to SPACE or SPC acquisitions over TSE acquisitions.

**Comment by akhanf** [comment]
Actually I see two different issues here:
1. when getting the list of all T2w images, e.g. to pick out the index-0 as the ref image, as done [here](https://github.com/khanlab/hippunfold/blob/947f19e527559e3384c09a1a5775959bfd3b4117/hippunfold/workflow/rules/preproc_t2.smk#L61), the ordering in the list has some randomness to it. I think it has to do with the use of `set()` in snakebids [here](https://github.com/akhanf/snakebids/blob/a36fac763ca580cf4b7b218c5e1c7c32756e01b4/snakebids/__init__.py#L339), so will need to create an issue in snakebids to resolve this.. Note that this also affects what reference image is chosen when there are multiple T2w images, ie not just when `--skip_preproc` is used.. 
2. Once the randomness is removed, there is still the issue of whether we can (or want to) enforce some re-sorting of this list. There, I am more hesitant, since it would rely on bids tags without a constrained vocabulary (e.g. acq- can have anything in it..), so would never be able to have a heuristic that always works..  Perhaps we should just make it more opaque to the user exactly what scans are being pulled into the workflow.  Maybe could have some added option for specifying the reference to use, but I think in almost cases a simple alphanumerical sort would be fine..

**Comment by akhanf** [comment]
Since the first problem is solved with snakebids v0.3.x #49  (by removing randomness in order), closing the issue.. The second problem is one that we don't really need to solve (since filters can be used to select the image(s) to use)
